### ISSUE TITLE
Service closure

### ISSUE THREAD

**Issue by continue98** [Teknikode/Teknik#46]
Hi. Give time for some services to change mail (like a month). Because can't change anything without the code to the main mail

**Comment by continue98** [comment]
@uncled1023

**Comment by uncled1023** [comment]
Hello, the notice was first posted in the first part of January.  The hard deadline is due to the contract ending.  The server and all it's data is now gone.

**Comment by continue98** [comment]
@uncled1023 We don't care as much about the data as we do about being able to get a code to change the mail. How much does a host cost per month?

And by the way I did not get a notification (it seemed to be on the main?), if so I used mail.teknik.io always and was rarely on the main

**Comment by continue98** [comment]
we could also raise the mail server to redirect messages from the teknik mail server for a while

**Comment by frozenpandaman** [comment]
Would have been nice to have gotten an email about this before deleting everything…!

**Comment by continue98** [comment]
@DanielFGray, @uncled1023  Dude, a lot of services ask for a code that is sent to the old mail before you change your mail. Can you set up some kind of redirect?

**Comment by DanielFGray** [comment]
Not sure why you mentioned me, I have nothing to do with this, except I may have sent a PR once or twice
