### ISSUE TITLE
Can't access any teknik.io services

### ISSUE THREAD

**Issue by camdendobrien** [Teknikode/Teknik#9]
I currently can't connect to any teknik.io services, neither can my friend. We're both in the UK, if that makes a difference?

**Comment by callumobrien-bluefruit** [comment]
Ok, it's working now

**Comment by camdendobrien** [comment]
Ok, it's working now.

**Comment by camdendobrien** [comment]
Now it's down again.

**Comment by uncled1023** [comment]
This should be resolved.  Closing
